local colors = require('utils').colors
local catppuccin = require('catppuccin')

catppuccin.setup({
  color_overrides = {
    all = {
      rosewater = colors.red,
      flamingo  = colors.red,
      pink      = colors.red,
      mauve     = colors.red,
      red       = colors.red,
      maroon    = colors.red,
      peach     = colors.red,
      yellow    = colors.yellow,
      green     = colors.green,
      teal      = colors.cyan,
      sky       = colors.blue,
      sapphire  = colors.blue,
      blue      = colors.blue,
      lavender  = colors.magenta,
      text      = colors.fg,
      subtext1  = colors.fg,
      subtext0  = colors.fg,
      overlay2  = colors.fg,
      overlay1  = colors.gray,
      overlay0  = colors.gray,
      surface2  = colors.gray,
      surface1  = colors.gray,
      surface0  = colors.gray,
      base      = colors.bg,
      mantle    = colors.bg,
      crust     = colors.bg,
    },
  },
  custom_highlights = function(_)
    return {
      ColorColumn                          = { bg = colors.bg },
      Conceal                              = { fg = colors.gray },
      Cursor                               = { fg = colors.bg, bg = colors.magenta },
      CursorColumn                         = { bg = colors.bg },
      CursorLine                           = { bg = colors.bg },
      CursorLineNr                         = { fg = colors.magenta },
      DiffAdd                              = { bg = colors.green },
      DiffChange                           = { fg = colors.bg, bg = colors.blue },
      DiffDelete                           = { fg = colors.bg, bg = colors.red },
      DiffText                             = { fg = colors.bg, bg = colors.blue },
      Directory                            = { fg = colors.green },
      EndOfBuffer                          = { fg = colors.black },
      ErrorMsg                             = { fg = colors.red },
      FloatBorder                          = { fg = colors.gray },
      FoldColumn                           = { fg = colors.gray },
      Folded                               = { fg = colors.gray },
      IncSearch                            = { fg = colors.bg, bg = colors.red },
      LineNr                               = { fg = colors.gray },
      MatchParen                           = { bg = colors.black },
      MoreMsg                              = { fg = colors.yellow },
      NonText                              = { fg = colors.fg, bg = colors.bg },
      Normal                               = { fg = colors.fg, bg = colors.bg },
      NormalFloat                          = { fg = colors.fg, bg = colors.black },
      Pmenu                                = { fg = colors.fg, bg = colors.black },
      PmenuSbar                            = { bg = colors.gray },
      PmenuSel                             = { fg = colors.black, bg = colors.magenta },
      PmenuThumb                           = { bg = colors.black },
      Question                             = { fg = colors.yellow },
      QuickFixLine                         = { fg = colors.magenta },
      Search                               = { fg = colors.bg, bg = colors.green },
      SignColumn                           = { fg = colors.fg },
      SpecialKey                           = { fg = colors.gray },
      SpellBad                             = { fg = colors.bg, bg = colors.red },
      SpellCap                             = { fg = colors.bg, bg = colors.blue },
      SpellLocal                           = { fg = colors.bg, bg = colors.cyan },
      SpellRare                            = { fg = colors.bg, bg = colors.magenta },
      Terminal                             = { fg = colors.fg, bg = colors.bg },
      ToolbarLine                          = { fg = colors.fg, },
      VertSplit                            = { fg = colors.gray, },
      Visual                               = { fg = colors.bg, bg = colors.green },
      VisualNOS                            = { fg = colors.bg, bg = colors.gray },
      WarningMsg                           = { fg = colors.yellow },
      Whitespace                           = { fg = colors.fg },
      WildMenu                             = { fg = colors.black, bg = colors.magenta },
      WinSeparator                         = { fg = colors.bg, bg = colors.green },
      ['@annotation']                      = { fg = colors.magenta },
      ['@attribute']                       = { fg = colors.magenta },
      ['@boolean']                         = { fg = colors.magenta },
      ['@character']                       = { fg = colors.yellow },
      ['@comment']                         = { fg = colors.gray },
      ['@conditional']                     = { fg = colors.red },
      ['@constant']                        = { fg = colors.magenta },
      ['@constant.builtin']                = { fg = colors.blue },
      ['@constant.macro']                  = { fg = colors.blue },
      ['@constructor']                     = { fg = colors.green },
      ['@exception']                       = { fg = colors.red },
      ['@field']                           = { fg = colors.orange },
      ['@float']                           = { fg = colors.purple },
      ['@function']                        = { fg = colors.green },
      ['@function.builtin']                = { fg = colors.blue },
      ['@function.macro']                  = { fg = colors.blue },
      ['@include']                         = { fg = colors.red },
      ['@keyword']                         = { fg = colors.red },
      ['@keyword.function']                = { fg = colors.red },
      ['@keyword.operator']                = { fg = colors.red },
      ['@label']                           = { fg = colors.orange },
      ['@method']                          = { fg = colors.green },
      ['@namespace']                       = { fg = colors.yellow },
      ['@none']                            = { fg = colors.fg },
      ['@number']                          = { fg = colors.magenta },
      ['@operator']                        = { fg = colors.red },
      ['@parameter']                       = { fg = colors.orange },
      ['@parameter.reference']             = { fg = colors.orange },
      ['@property']                        = { fg = colors.orange },
      ['@punctuation.bracket']             = { fg = colors.fg },
      ['@punctuation.delimiter']           = { fg = colors.fg },
      ['@punctuation.special']             = { fg = colors.blue },
      ['@repeat']                          = { fg = colors.red },
      ['@storageclass']                    = { fg = colors.red },
      ['@string']                          = { fg = colors.yellow },
      ['@string.escape']                   = { fg = colors.yellow },
      ['@string.regex']                    = { fg = colors.yellow },
      ['@symbol']                          = { fg = colors.fg },
      ['@tag']                             = { fg = colors.orange },
      ['@tag.delimiter']                   = { fg = colors.green },
      ['@text']                            = { fg = colors.green },
      ['@strike']                          = { fg = colors.gray },
      ['@math']                            = { fg = colors.blue },
      ['@type']                            = { fg = colors.blue },
      ['@type.builtin']                    = { fg = colors.yellow },
      ['@uri']                             = { fg = colors.blue },
      ['@variable']                        = { fg = colors.fg },
      ['@variable.builtin']                = { fg = colors.blue },
      CmpItemAbbr                          = { fg = colors.fg, bg = colors.black },
      CmpItemAbbrDeprecated                = { fg = colors.gray, bg = colors.black },
      CmpItemMenu                          = { fg = colors.fg, bg = colors.black },
      CmpItemKind                          = { fg = colors.yellow, bg = colors.black },
      CmpItemKindText                      = { fg = colors.fg, bg = colors.black },
      CmpItemKindMethod                    = { fg = colors.green, bg = colors.black },
      CmpItemKindFunction                  = { fg = colors.green, bg = colors.black },
      CmpItemKindConstructor               = { fg = colors.green, bg = colors.black },
      CmpItemKindField                     = { fg = colors.green, bg = colors.black },
      CmpItemKindVariable                  = { fg = colors.blue, bg = colors.black },
      CmpItemKindClass                     = { fg = colors.yellow, bg = colors.black },
      CmpItemKindInterface                 = { fg = colors.yellow, bg = colors.black },
      CmpItemKindModule                    = { fg = colors.yellow, bg = colors.black },
      CmpItemKindProperty                  = { fg = colors.blue, bg = colors.black },
      CmpItemKindUnit                      = { fg = colors.purple, bg = colors.black },
      CmpItemKindValue                     = { fg = colors.purple, bg = colors.black },
      CmpItemKindEnum                      = { fg = colors.yellow, bg = colors.black },
      CmpItemKindKeyword                   = { fg = colors.red, bg = colors.black },
      CmpItemKindSnippet                   = { fg = colors.cyan, bg = colors.black },
      CmpItemKindColor                     = { fg = colors.cyan, bg = colors.black },
      CmpItemKindFile                      = { fg = colors.cyan, bg = colors.black },
      CmpItemKindReference                 = { fg = colors.cyan, bg = colors.black },
      CmpItemKindFolder                    = { fg = colors.cyan, bg = colors.black },
      CmpItemKindEnumMember                = { fg = colors.magenta, bg = colors.black },
      CmpItemKindConstant                  = { fg = colors.blue, bg = colors.black },
      CmpItemKindStruct                    = { fg = colors.yellow, bg = colors.black },
      CmpItemKindEvent                     = { fg = colors.orange, bg = colors.black },
      CmpItemKindOperator                  = { fg = colors.orange, bg = colors.black },
      CmpItemKindTypeParameter             = { fg = colors.yellow, bg = colors.black },
      TelescopeBorder                      = { fg = colors.gray, bg = colors.bg },
      TelescopePromptPrefix                = { fg = colors.red, bg = colors.bg },
      TelescopeSelection                   = { fg = colors.magenta, bg = colors.bg },
      ErrorText                            = { fg = colors.red, bg = colors.bg },
      WarningText                          = { fg = colors.yellow, bg = colors.bg },
      InfoText                             = { fg = colors.blue, bg = colors.bg },
      HintText                             = { fg = colors.green, bg = colors.bg },
      ErrorLine                            = { fg = colors.red, bg = colors.bg },
      WarningLine                          = { fg = colors.yellow, bg = colors.bg },
      InfoLine                             = { fg = colors.blue, bg = colors.bg },
      HintLine                             = { fg = colors.green, bg = colors.bg },
      ErrorFloat                           = { fg = colors.red, bg = colors.bg },
      WarningFloat                         = { fg = colors.yellow, bg = colors.bg },
      InfoFloat                            = { fg = colors.blue, bg = colors.bg },
      HintFloat                            = { fg = colors.green, bg = colors.bg },
      VirtualTextError                     = { fg = colors.red, bg = colors.bg },
      VirtualTextWarning                   = { fg = colors.yellow, bg = colors.bg },
      VirtualTextInfo                      = { fg = colors.blue, bg = colors.bg },
      VirtualTextHint                      = { fg = colors.green, bg = colors.bg },
      WinBarNC                             = { fg = colors.gray, bg = colors.bg },
      DiagnosticFloatingError              = { fg = colors.red, bg = colors.bg },
      DiagnosticFloatingWarn               = { fg = colors.yellow, bg = colors.bg },
      DiagnosticFloatingInfo               = { fg = colors.blue, bg = colors.bg },
      DiagnosticFloatingHint               = { fg = colors.green, bg = colors.bg },
      DiagnosticError                      = { fg = colors.red, bg = colors.bg },
      DiagnosticWarn                       = { fg = colors.yellow, bg = colors.bg },
      DiagnosticInfo                       = { fg = colors.blue, bg = colors.bg },
      DiagnosticHint                       = { fg = colors.green, bg = colors.bg },
      DiagnosticVirtualTextError           = { fg = colors.red, bg = colors.bg },
      DiagnosticVirtualTextWarn            = { fg = colors.yellow, bg = colors.bg },
      DiagnosticVirtualTextInfo            = { fg = colors.blue, bg = colors.bg },
      DiagnosticVirtualTextHint            = { fg = colors.green, bg = colors.bg },
      DiagnosticUnderlineError             = { fg = colors.red, bg = colors.bg },
      DiagnosticUnderlineWarn              = { fg = colors.yellow, bg = colors.bg },
      DiagnosticUnderlineInfo              = { fg = colors.blue, bg = colors.bg },
      DiagnosticUnderlineHint              = { fg = colors.green, bg = colors.bg },
      DiagnosticSignError                  = { fg = colors.red, bg = colors.bg },
      DiagnosticSignWarn                   = { fg = colors.yellow, bg = colors.bg },
      DiagnosticSignInfo                   = { fg = colors.blue, bg = colors.bg },
      DiagnosticSignHint                   = { fg = colors.green, bg = colors.bg },
      LspDiagnosticsFloatingError          = { fg = colors.red, bg = colors.bg },
      LspDiagnosticsFloatingWarning        = { fg = colors.yellow, bg = colors.bg },
      LspDiagnosticsFloatingInformation    = { fg = colors.blue, bg = colors.bg },
      LspDiagnosticsFloatingHint           = { fg = colors.green, bg = colors.bg },
      LspDiagnosticsDefaultError           = { fg = colors.red, bg = colors.bg },
      LspDiagnosticsDefaultWarning         = { fg = colors.yellow, bg = colors.bg },
      LspDiagnosticsDefaultInformation     = { fg = colors.blue, bg = colors.bg },
      LspDiagnosticsDefaultHint            = { fg = colors.green, bg = colors.bg },
      LspDiagnosticsVirtualTextError       = { fg = colors.red, bg = colors.bg },
      LspDiagnosticsVirtualTextWarning     = { fg = colors.yellow, bg = colors.bg },
      LspDiagnosticsVirtualTextInformation = { fg = colors.blue, bg = colors.bg },
      LspDiagnosticsVirtualTextHint        = { fg = colors.green, bg = colors.bg },
      LspDiagnosticsUnderlineError         = { fg = colors.red, bg = colors.bg },
      LspDiagnosticsUnderlineWarning       = { fg = colors.yellow, bg = colors.bg },
      LspDiagnosticsUnderlineInformation   = { fg = colors.blue, bg = colors.bg },
      LspDiagnosticsUnderlineHint          = { fg = colors.green, bg = colors.bg },
      LspDiagnosticsSignError              = { fg = colors.red, bg = colors.bg },
      LspDiagnosticsSignWarning            = { fg = colors.yellow, bg = colors.bg },
      LspDiagnosticsSignInformation        = { fg = colors.blue, bg = colors.bg },
      LspDiagnosticsSignHint               = { fg = colors.green, bg = colors.bg },
      healthError                          = { fg = colors.red, bg = colors.bg },
      healthSuccess                        = { fg = colors.green, bg = colors.bg },
      healthWarning                        = { fg = colors.yellow, bg = colors.bg },
    }
  end,
  no_italic = true,
  no_bold = true,
  styles = {
    comments = {},
    conditionals = {},
    loops = {},
    functions = {},
    keywords = {},
    strings = {},
    variables = {},
    numbers = {},
    booleans = {},
    properties = {},
    types = {},
    operators = {},
  },
  integrations = {
    cmp = true,
    gitsigns = true,
    telescope = true,
  },
})

catppuccin.compile()

vim.cmd.colorscheme "catppuccin"
