local colors = {
  fg = "#bda988",
  bg = "#262626",
  black = "#32302f",
  red = "#c7544e",
  green = "#97a35b",
  yellow = "#bf9d4e",
  blue = "#6f9e93",
  magenta = "#bd7388",
  cyan = "#84ad7d",
  white = "#e0cfaf",
  orange = "#c97e42",
  gray = "#7d7064",
}

local catppuccin = require('catppuccin')

catppuccin.setup({
  color_overrides = {
    all = {
      rosewater = colors.red,
      flamingo  = colors.red,
      pink      = colors.red,
      mauve     = colors.red,
      red       = colors.red,
      maroon    = colors.red,
      peach     = colors.red,
      yellow    = colors.yellow,
      green     = colors.green,
      teal      = colors.cyan,
      sky       = colors.blue,
      sapphire  = colors.blue,
      blue      = colors.blue,
      lavender  = colors.magenta,
      text      = colors.fg,
      subtext1  = colors.fg,
      subtext0  = colors.fg,
      overlay2  = colors.fg,
      overlay1  = colors.gray,
      overlay0  = colors.gray,
      surface2  = colors.gray,
      surface1  = colors.gray,
      surface0  = colors.gray,
      base      = colors.bg,
      mantle    = colors.bg,
      crust     = colors.bg,
    },
  },
  custom_highlights = function(_)
    return {
      ['@annotation']            = { fg = colors.magenta, style = {} },
      ['@attribute']             = { fg = colors.magenta, style = {} },
      ['@boolean']               = { fg = colors.magenta, style = {} },
      ['@character']             = { fg = colors.yellow, style = {} },
      ['@comment']               = { fg = colors.gray, style = {} },
      ['@conditional']           = { fg = colors.red, style = {} },
      ['@constant']              = { fg = colors.magenta, style = {} },
      ['@constant.builtin']      = { fg = colors.blue, style = {} },
      ['@constant.macro']        = { fg = colors.blue, style = {} },
      ['@constructor']           = { fg = colors.green, style = {} },
      ['@exception']             = { fg = colors.red, style = {} },
      ['@field']                 = { fg = colors.orange, style = {} },
      ['@float']                 = { fg = colors.purple, style = {} },
      ['@function']              = { fg = colors.green, style = {} },
      ['@function.builtin']      = { fg = colors.blue, style = {} },
      ['@function.macro']        = { fg = colors.blue, style = {} },
      ['@include']               = { fg = colors.red, style = {} },
      ['@keyword']               = { fg = colors.red, style = {} },
      ['@keyword.function']      = { fg = colors.red, style = {} },
      ['@keyword.operator']      = { fg = colors.red, style = {} },
      ['@label']                 = { fg = colors.orange, style = {} },
      ['@method']                = { fg = colors.green, style = {} },
      ['@namespace']             = { fg = colors.yellow, style = {} },
      ['@none']                  = { fg = colors.fg, style = {} },
      ['@number']                = { fg = colors.magenta, style = {} },
      ['@operator']              = { fg = colors.red, style = {} },
      ['@parameter']             = { fg = colors.orange, style = {} },
      ['@parameter.reference']   = { fg = colors.orange, style = {} },
      ['@property']              = { fg = colors.orange, style = {} },
      ['@punctuation.bracket']   = { fg = colors.fg, style = {} },
      ['@punctuation.delimiter'] = { fg = colors.fg, style = {} },
      ['@punctuation.special']   = { fg = colors.blue, style = {} },
      ['@repeat']                = { fg = colors.red, style = {} },
      ['@storageclass']          = { fg = colors.red, style = {} },
      ['@string']                = { fg = colors.yellow, style = {} },
      ['@string.escape']         = { fg = colors.yellow, style = {} },
      ['@string.regex']          = { fg = colors.yellow, style = {} },
      ['@symbol']                = { fg = colors.fg, style = {} },
      ['@tag']                   = { fg = colors.orange, style = {} },
      ['@tag.delimiter']         = { fg = colors.green, style = {} },
      ['@text']                  = { fg = colors.green, style = {} },
      ['@strike']                = { fg = colors.gray, style = {} },
      ['@math']                  = { fg = colors.blue, style = {} },
      ['@type']                  = { fg = colors.blue, style = {} },
      ['@type.builtin']          = { fg = colors.yellow, style = {} },
      ['@uri']                   = { fg = colors.blue, style = {} },
      ['@variable']              = { fg = colors.fg, style = {} },
      ['@variable.builtin']      = { fg = colors.blue, style = {} },
      CmpItemAbbr                = { fg = colors.fg, style = {} },
      CmpItemAbbrDeprecated      = { fg = colors.gray, style = {} },
      CmpItemMenu                = { fg = colors.fg, style = {} },
      CmpItemKind                = { fg = colors.yellow, style = {} },
      CmpItemKindText            = { fg = colors.fg, style = {} },
      CmpItemKindMethod          = { fg = colors.green, style = {} },
      CmpItemKindFunction        = { fg = colors.green, style = {} },
      CmpItemKindConstructor     = { fg = colors.green, style = {} },
      CmpItemKindField           = { fg = colors.green, style = {} },
      CmpItemKindVariable        = { fg = colors.blue, style = {} },
      CmpItemKindClass           = { fg = colors.yellow, style = {} },
      CmpItemKindInterface       = { fg = colors.yellow, style = {} },
      CmpItemKindModule          = { fg = colors.yellow, style = {} },
      CmpItemKindProperty        = { fg = colors.blue, style = {} },
      CmpItemKindUnit            = { fg = colors.purple, style = {} },
      CmpItemKindValue           = { fg = colors.purple, style = {} },
      CmpItemKindEnum            = { fg = colors.yellow, style = {} },
      CmpItemKindKeyword         = { fg = colors.red, style = {} },
      CmpItemKindSnippet         = { fg = colors.aqua, style = {} },
      CmpItemKindColor           = { fg = colors.aqua, style = {} },
      CmpItemKindFile            = { fg = colors.aqua, style = {} },
      CmpItemKindReference       = { fg = colors.aqua, style = {} },
      CmpItemKindFolder          = { fg = colors.aqua, style = {} },
      CmpItemKindEnumMember      = { fg = colors.purple, style = {} },
      CmpItemKindConstant        = { fg = colors.blue, style = {} },
      CmpItemKindStruct          = { fg = colors.yellow, style = {} },
      CmpItemKindEvent           = { fg = colors.orange, style = {} },
      CmpItemKindOperator        = { fg = colors.orange, style = {} },
      CmpItemKindTypeParameter   = { fg = colors.yellow, style = {} },
      TelescopeBorder            = { fg = colors.gray, style = {} },
      TelescopePromptPrefix      = { fg = colors.red, style = {} },
      TelescopeSelection         = { fg = colors.magenta, style = {} },
    }
  end,
  transparent_background = true,
  no_italic = true,
  no_bold = true,
  styles = {
    comments = {},
    conditionals = {},
    loops = {},
    functions = {},
    keywords = {},
    strings = {},
    variables = {},
    numbers = {},
    booleans = {},
    properties = {},
    types = {},
    operators = {},
  },
  integrations = {
    cmp = true,
    gitsigns = true,
    nvimtree = true,
    telescope = true,
    notify = false,
    mini = false,
  },
})

catppuccin.compile()

vim.cmd.colorscheme "catppuccin"
