vim.opt.autowrite = true           -- Enable auto write
vim.opt.breakindent = true         -- Enable break indent
vim.opt.clipboard = "unnamedplus"  -- Sync with system clipboard
vim.opt.completeopt = "menu,menuone,noselect,noinsert"
vim.opt.conceallevel = 0           -- No concealment
vim.opt.confirm = true             -- Confirm to save changes before exiting modified buffer
vim.opt.cursorline = true          -- Enable highlighting of the current line
vim.opt.expandtab = true           -- Use spaces instead of tabs
vim.opt.foldlevel = 99             -- Don't fold anything
vim.opt.formatoptions = "jcroqlnt" -- tcqj
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.hlsearch = false       -- Set highlight on search
vim.opt.ignorecase = true      -- Ignore case
vim.opt.inccommand = "nosplit" -- preview incremental substitute
vim.opt.list = true            -- Show some invisible characters (tabs...
vim.opt.mouse = 'a'            -- Enable mouse mode
vim.opt.number = true          -- Print line number
vim.opt.pumheight = 10         -- Maximum number of entries in a popup
vim.opt.relativenumber = true  -- Relative line numbers
vim.opt.scrolloff = 4          -- Lines of context
vim.opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
vim.opt.shiftround = true      -- Round indent
vim.opt.shiftwidth = 4         -- Size of an indent
vim.opt.shortmess:append { W = true, I = true, c = true }
vim.opt.showmode = false       -- Dont show mode since we have a statusline
vim.opt.sidescroll = 0         -- No sidescrolling
vim.opt.signcolumn = "yes"     -- Always show the signcolumn
vim.opt.smartcase = true       -- Don't ignore case with capitals
vim.opt.smartindent = true     -- Insert indents automatically
vim.opt.spelllang = { "en" }
vim.opt.splitbelow = true      -- Put new windows below current
vim.opt.splitright = true      -- Put new windows right of current
vim.opt.tabstop = 4            -- Number of spaces tabs count for
vim.opt.termguicolors = true   -- True color support
vim.opt.textwidth = 80
vim.opt.timeout = true
vim.opt.timeoutlen = 300
vim.opt.undofile = true                -- Save undo history
vim.opt.undolevels = 10000
vim.opt.updatetime = 250               -- Save swap file and trigger CursorHold
vim.opt.wildmode = "longest:full,full" -- Command-line completion mode
vim.opt.winminwidth = 5                -- Minimum window width
vim.opt.wrap = false                   -- Disable line wrap
