local colors = {
    fg = "#bda988",
    bg = "#262626",
    gray = "#7d7064",
    black = "#32302f",
    red = "#c7544e",
    green = "#97a35b",
    yellow = "#bf9d4e",
    blue = "#6f9e93",
    magenta = "#bd7388",
    cyan = "#84ad7d",
    white = "#e0cfaf",
}

local default = {
    fg = colors.fg,
    bg = colors.bg,
    sp = colors.bg,
    bold = false,
    italic = false,
}

return {
    {
        "akinsho/bufferline.nvim",
        event = "VeryLazy",
        keys = {
            { "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "previous buffer" },
            { "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "next buffer" },
            { "<leader>bd", "<cmd>bd<cr>", desc = "close buffer" },
            { "<leader>bp", "<cmd>BufferLineTogglePin<cr>", desc = "toggle pin" },
            { "<leader>bP", "<cmd>BufferLineGroupClose ungrouped<cr>", desc = "delete unpinned buffers" },
        },
        opts = {
            options = {
                diagnostics = false,
                show_buffer_icons = false,
                show_buffer_close_icons = false,
                show_buffer_default_icon = false,
                show_duplicate_prefix = false,
                show_close_icon = false,
                show_tab_indicators = false,
                always_show_bufferline = false,
                separator_style = "thin",
            },
            highlights = {
                fill = {
                    fg = colors.bg,
                    bg = colors.bg,
                },
                background = {
                    fg = colors.gray,
                    bg = colors.bg,
                },
                tab = {
                    fg = colors.fg,
                    bg = colors.bg,
                },
                tab_selected = {
                    fg = colors.gray,
                    bg = colors.bg,
                },
                tab_close = default,
                close_button_visible = default,
                close_button_selected = default,
                buffer_visible = default,
                buffer_selected = default,
                numbers = default,
                numbers_visible = default,
                numbers_selected = default,
                diagnostic = default,
                diagnostic_visible = default,
                diagnostic_selected = default,
                hint = default,
                hint_visible = default,
                hint_selected = default,
                hint_diagnostic = default,
                hint_diagnostic_visible = default,
                hint_diagnostic_selected = default,
                info = default,
                info_visible = default,
                info_selected = default,
                info_diagnostic = default,
                info_diagnostic_visible = default,
                info_diagnostic_selected = default,
                warning = default,
                warning_visible = default,
                warning_selected = default,
                warning_diagnostic = default,
                warning_diagnostic_visible = default,
                warning_diagnostic_selected = default,
                error = default,
                error_visible = default,
                error_selected = default,
                error_diagnostic = default,
                error_diagnostic_visible = default,
                error_diagnostic_selected = default,
                modified = default,
                modified_visible = default,
                modified_selected = default,
                duplicate_selected = default,
                duplicate_visible = default,
                duplicate = default,
                separator_selected = default,
                separator_visible = default,
                separator = default,
                indicator_selected = default,
                pick_selected = default,
                pick_visible = default,
                pick = default,
                offset_separator = default,
            },
        },
    },
}
